// DumpBpGraphsCommandlet.cpp
#include "Commandlets/DumpBpGraphsCommandlet.h"

#include "Blueprint/WidgetBlueprintGeneratedClass.h"
#include "Blueprint/WidgetTree.h"
#include "Components/Widget.h"
#include "EdGraph/EdGraph.h"
#include "EdGraph/EdGraphNode.h"
#include "EdGraph/EdGraphPin.h"
#include "Engine/Blueprint.h"
#include "Engine/DataTable.h"
#include "Items/Data/Inv_ItemData.h"
#include "Misc/FileHelper.h"
#include "Misc/Paths.h"
#include "Player/GAS_PlayerController.h"

static FString GOut;

static void DLog(const FString& Line)
{
	GOut += Line + TEXT("\n");
	UE_LOG(LogTemp, Log, TEXT("[DumpBP] %s"), *Line);
}

static void DumpPin(const UEdGraphPin* Pin, int32 Indent)
{
	if (!Pin) return;
	FString Linked;
	for (const UEdGraphPin* L : Pin->LinkedTo)
	{
		if (!L || !L->GetOwningNode()) continue;
		Linked += FString::Printf(TEXT("%s.%s;"), *L->GetOwningNode()->GetNodeTitle(ENodeTitleType::FullTitle).ToString(), *L->PinName.ToString());
	}
	DLog(FString::Printf(TEXT("%*sPIN %s | dir=%s | cat=%s | sub=%s | def=%s | auto=%s | linked=[%s]"),
		Indent, TEXT(""),
		*Pin->PinName.ToString(),
		*UEnum::GetValueAsString(Pin->Direction),
		*Pin->PinType.PinCategory.ToString(),
		*Pin->PinType.PinSubCategory.ToString(),
		*Pin->DefaultValue,
		*Pin->AutogeneratedDefaultValue,
		*Linked));
}

static void DumpNode(const UEdGraphNode* Node)
{
	if (!Node) return;
	const FString ClassName = Node->GetClass() ? Node->GetClass()->GetName() : TEXT("?");
	const FString Title = Node->GetNodeTitle(ENodeTitleType::FullTitle).ToString();
	const FString Comment = Node->NodeComment;
	DLog(FString::Printf(TEXT("  NODE %s | %s | comment=%s"), *ClassName, *Title, *Comment));
	for (const UEdGraphPin* Pin : Node->Pins)
	{
		DumpPin(Pin, 4);
	}
}

static void DumpGraph(const UEdGraph* Graph, const FString& Label)
{
	if (!Graph) return;
	DLog(FString::Printf(TEXT("--- GRAPH %s (%s) ---"), *Label, *Graph->GetClass()->GetName()));
	for (const UEdGraphNode* Node : Graph->Nodes)
	{
		DumpNode(Node);
	}
}

static void DumpWidgetTree(UWidgetTree* Tree)
{
	if (!Tree) return;
	DLog(TEXT("--- WIDGET TREE (archetype) ---"));
	TFunction<void(UWidget*, int32)> DumpW;
	DumpW = [&DumpW](UWidget* W, int32 Indent)
	{
		if (!W) return;
		const FString ClassName = W->GetClass() ? W->GetClass()->GetName() : TEXT("?");
		const FString WName = W->GetName();
		DLog(FString::Printf(TEXT("%*sWIDGET %s (%s)"), Indent, TEXT(""), *ClassName, *WName));
	};
	Tree->ForEachWidget([&DumpW](UWidget* W)
	{
		if (W) DumpW(W, 0);
	});
}

static void DumpWidgetBlueprint(const FString& AssetPath)
{
	DLog(FString::Printf(TEXT("============================================================")));
	UBlueprint* BP = LoadObject<UBlueprint>(nullptr, *AssetPath);
	if (!BP)
	{
		DLog(FString::Printf(TEXT("NOT FOUND: %s"), *AssetPath));
		return;
	}
	DLog(FString::Printf(TEXT("ASSET %s class=%s parent=%s"), *AssetPath,
		*BP->GetClass()->GetName(),
		BP->ParentClass ? *BP->ParentClass->GetName() : TEXT("?")));
	DLog(FString::Printf(TEXT("GeneratedClass = %s"), BP->GeneratedClass ? *BP->GeneratedClass->GetName() : TEXT("?")));

	UWidgetBlueprintGeneratedClass* Gen = Cast<UWidgetBlueprintGeneratedClass>(BP->GeneratedClass);
	if (Gen)
	{
		DLog(TEXT("  ** is a widget blueprint **"));
		if (UWidgetTree* Tree = Gen->GetWidgetTreeArchetype())
		{
			DumpWidgetTree(Tree);
		}
	}

	for (const UEdGraph* G : BP->UbergraphPages)
	{
		DumpGraph(G, G->GetName());
	}
	for (const UEdGraph* G : BP->FunctionGraphs)
	{
		DumpGraph(G, G->GetName());
	}
	for (const UEdGraph* G : BP->MacroGraphs)
	{
		DumpGraph(G, G->GetName());
	}
}

static FString GetPropValueStr(UClass* Class, const void* Instance, const TCHAR* PropName)
{
	if (!Class || !Instance) return TEXT("NULL");
	const FProperty* Prop = Class->FindPropertyByName(PropName);
	if (!Prop)
	{
		// search super classes
		for (UClass* C = Class->GetSuperClass(); C; C = C->GetSuperClass())
		{
			Prop = C->FindPropertyByName(PropName);
			if (Prop) break;
		}
	}
	if (!Prop) return FString::Printf(TEXT("<no prop %s>"), PropName);

	if (const FObjectProperty* ObjProp = CastField<FObjectProperty>(Prop))
	{
		if (UObject* Obj = ObjProp->GetObjectPropertyValue_InContainer(Instance))
		{
			return Obj->GetPathName();
		}
		return TEXT("NULL");
	}
	if (const FIntProperty* IntProp = CastField<FIntProperty>(Prop))
	{
		return FString::Printf(TEXT("%d"), IntProp->GetPropertyValue_InContainer(Instance));
	}
	if (const FDoubleProperty* DblProp = CastField<FDoubleProperty>(Prop))
	{
		return FString::Printf(TEXT("%f"), DblProp->GetPropertyValue_InContainer(Instance));
	}
	if (const FStructProperty* StructProp = CastField<FStructProperty>(Prop))
	{
		FString Out;
		StructProp->ExportText_InContainer(0, Out, Instance, nullptr, nullptr, 0, nullptr);
		return Out;
	}
	return TEXT("<unhandled type>");
}

static void DumpPlayerControllerDefaults()
{
	DLog(TEXT("============================================================"));
	DLog(TEXT("BP_GAS_PlayerController CDO:"));
	UClass* CppClass = AGAS_PlayerController::StaticClass();
	const UObject* CppCDO = CppClass->GetDefaultObject();
	DLog(FString::Printf(TEXT("  C++ CDO ItemDataTable=%s"), *GetPropValueStr(CppClass, CppCDO, TEXT("ItemDataTable"))));
	DLog(FString::Printf(TEXT("  C++ CDO MaxSlots=%s"), *GetPropValueStr(CppClass, CppCDO, TEXT("MaxSlots"))));
	DLog(FString::Printf(TEXT("  C++ CDO HotbarSlotCount=%s"), *GetPropValueStr(CppClass, CppCDO, TEXT("HotbarSlotCount"))));
	DLog(FString::Printf(TEXT("  C++ CDO TraceLength=%s"), *GetPropValueStr(CppClass, CppCDO, TEXT("TraceLength"))));
	DLog(FString::Printf(TEXT("  C++ CDO InventoryWidgetClass=%s"), *GetPropValueStr(CppClass, CppCDO, TEXT("InventoryWidgetClass"))));
	DLog(FString::Printf(TEXT("  C++ CDO HotbarWidgetClass=%s"), *GetPropValueStr(CppClass, CppCDO, TEXT("HotbarWidgetClass"))));
	DLog(FString::Printf(TEXT("  C++ CDO HUDWidgetClass=%s"), *GetPropValueStr(CppClass, CppCDO, TEXT("HUDWidgetClass"))));

	UClass* BPC = LoadObject<UClass>(nullptr, TEXT("/Game/GAS/Player/BP_GAS_PlayerController.BP_GAS_PlayerController_C"));
	if (!BPC)
	{
		BPC = LoadObject<UClass>(nullptr, TEXT("/Game/GAS/Player/BP_GAS_PlayerController_C"));
	}
	if (BPC)
	{
		const UObject* BPCDO = BPC->GetDefaultObject();
		DLog(FString::Printf(TEXT("  [BP] ItemDataTable=%s"), *GetPropValueStr(BPC, BPCDO, TEXT("ItemDataTable"))));
		DLog(FString::Printf(TEXT("  [BP] MaxSlots=%s"), *GetPropValueStr(BPC, BPCDO, TEXT("MaxSlots"))));
		DLog(FString::Printf(TEXT("  [BP] HotbarSlotCount=%s"), *GetPropValueStr(BPC, BPCDO, TEXT("HotbarSlotCount"))));
		DLog(FString::Printf(TEXT("  [BP] TraceLength=%s"), *GetPropValueStr(BPC, BPCDO, TEXT("TraceLength"))));
		DLog(FString::Printf(TEXT("  [BP] InventoryWidgetClass=%s"), *GetPropValueStr(BPC, BPCDO, TEXT("InventoryWidgetClass"))));
		DLog(FString::Printf(TEXT("  [BP] HotbarWidgetClass=%s"), *GetPropValueStr(BPC, BPCDO, TEXT("HotbarWidgetClass"))));
		DLog(FString::Printf(TEXT("  [BP] HUDWidgetClass=%s"), *GetPropValueStr(BPC, BPCDO, TEXT("HUDWidgetClass"))));
	}
	else
	{
		DLog(TEXT("  BP_GAS_PlayerController_C class NOT FOUND!"));
	}
}

static void DumpDataTable()
{
	DLog(TEXT("============================================================"));
	UDataTable* DT = LoadObject<UDataTable>(nullptr, TEXT("/Game/GAS/Items/DT_Items"));
	if (!DT)
	{
		DLog(TEXT("DT_Items NOT FOUND"));
		return;
	}
	DLog(FString::Printf(TEXT("DT_Items row struct: %s, %d rows"),
		DT->GetRowStruct() ? *DT->GetRowStruct()->GetName() : TEXT("?"),
		DT->GetRowMap().Num()));
	for (const TPair<FName, uint8*>& Pair : DT->GetRowMap())
	{
		if (const FInv_ItemDataRow* Row = reinterpret_cast<const FInv_ItemDataRow*>(Pair.Value))
		{
			DLog(FString::Printf(TEXT("  ROW %s | Name=%s | MaxStack=%d | Icon=%s | Mesh=%s"),
				*Pair.Key.ToString(),
				*Row->ItemName.ToString(),
				Row->MaxStackSize,
				*Row->ItemIcon.ToSoftObjectPath().ToString(),
				*Row->WorldMesh.ToSoftObjectPath().ToString()));
		}
	}
}

int32 UDumpBpGraphsCommandlet::Main(const FString& Params)
{
	GOut.Empty();
	DLog(TEXT("=== DumpBpGraphsCommandlet started ==="));

	static const TArray<FString> Assets = {
		TEXT("/Game/GAS/UI/Inventory/WBP_ItemSlot"),
		TEXT("/Game/GAS/UI/Inventory/WBP_Inventory"),
		TEXT("/Game/GAS/UI/Inventory/WBP_Hotbar"),
		TEXT("/Game/GAS/UI/Inventory/WBP_DragVisual"),
		TEXT("/Game/GAS/UI/HUD/WBP_Inv_HUDWidget"),
		TEXT("/Game/GAS/UI/HUD/WBP_Inv_PickupMessage"),
		TEXT("/Game/GAS/UI/Inventory/WBP_DropZone"),
	};
	for (const FString& Asset : Assets)
	{
		DumpWidgetBlueprint(Asset);
	}

	DumpPlayerControllerDefaults();
	DumpDataTable();

	const FString OutPath = FPaths::ProjectDir() / TEXT("dump_bp_graphs.txt");
	FFileHelper::SaveStringToFile(GOut, *OutPath, FFileHelper::EEncodingOptions::ForceUTF8);
	DLog(FString::Printf(TEXT("WROTE %d chars to %s"), GOut.Len(), *OutPath));
	return 0;
}
